#!/usr/bin/env bash

set -e

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOTDIR="/home/saya/simple_shell"

# Check if the directory is a Git repository
if ! git -C "$ROOTDIR" rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    echo "Error: Not a Git repository. Please initialize the repository first."
    exit 1
fi

# Proceed with generating AUTHORS file
set -x

# see also ".mailmap" for how email addresses and names are deduplicated
cat > "${ROOTDIR}/AUTHORS" <<- EOF
_       # File @generated by generate_authors.sh. DO NOT EDIT.
        # This file lists all contributors to the repository.
        # See hack/generate-authors.sh to make modifications.

        $(git -C "$ROOTDIR" log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf)
EOF

